web-screenshot-webapp/config/routes.rb
Rails.application.routes.draw do
  resources :screenshots
  resources :screenshots, param: :key, constraints: { key: /[a-zA-Z0-9\.]+/ }, only: %i[index new create show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

web-screenshot-webapp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

web-screenshot-webapp/app/models/screenshot.rb
class Screenshot < ApplicationRecord
  validates :url, presence: true

  after_create :invoke_screenshot

  def object
    @object ||= begin
      client = Aws::S3::Client.new(region: 'us-east-1')
      resource = Aws::S3::Resource.new(client: client)
      bucket = resource.bucket('web-screenshot-images-okonomi')
      bucket.object("#{id}.png")
    end
  end

  def image_exists?
    object.exists?
  end

  def screenshot_url
    @screenshot_url ||= object.presigned_url(:get)
  end

  private

  def invoke_screenshot
    client = Aws::Lambda::Client.new(region: 'us-east-1')
    client.invoke(
      function_name: 'web-screenshot-serverless-dev-screenshot',
      payload: {
        id: id,
        url: url
      }.to_json,
      invocation_type: 'Event',
    )
  end
end

web-screenshot-webapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

web-screenshot-webapp/app/controllers/screenshots_controller.rb
class ScreenshotsController < ApplicationController
  before_action :set_screenshot, only: [:show, :edit, :update, :destroy]

  # GET /screenshots
  # GET /screenshots.json
  def index
    @screenshots = Screenshot.all
  end

  # GET /screenshots/1
  # GET /screenshots/1.json
  def show
  end

  # GET /screenshots/new
  def new
    @screenshot = Screenshot.new
  end

  # GET /screenshots/1/edit
  def edit
  end

  # POST /screenshots
  # POST /screenshots.json
  def create
    @screenshot = Screenshot.new(screenshot_params)

    respond_to do |format|
      if @screenshot.save
        format.html { redirect_to @screenshot, notice: 'Screenshot was successfully created.' }
        format.json { render :show, status: :created, location: @screenshot }
      else
        format.html { render :new }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /screenshots/1
  # PATCH/PUT /screenshots/1.json
  def update
    respond_to do |format|
      if @screenshot.update(screenshot_params)
        format.html { redirect_to @screenshot, notice: 'Screenshot was successfully updated.' }
        format.json { render :show, status: :ok, location: @screenshot }
      else
        format.html { render :edit }
        format.json { render json: @screenshot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /screenshots/1
  # DELETE /screenshots/1.json
  def destroy
    @screenshot.destroy
    respond_to do |format|
      format.html { redirect_to screenshots_url, notice: 'Screenshot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_screenshot
      @screenshot = Screenshot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def screenshot_params
      params.require(:screenshot).permit(:url)
    end
end

web-screenshot-webapp/app/helpers/application_helper.rb
module ApplicationHelper
end

web-screenshot-webapp/app/helpers/screenshots_helper.rb
module ScreenshotsHelper
end

web-screenshot-webapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WebScreenshotWebapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

web-screenshot-webapp/app/views/screenshots/_form.html.erb
<%= form_with(model: screenshot, local: true) do |form| %>
  <% if screenshot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(screenshot.errors.count, "error") %> prohibited this screenshot from being saved:</h2>

      <ul>
        <% screenshot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, size: 100 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

web-screenshot-webapp/app/views/screenshots/edit.html.erb
<h1>Editing Screenshot</h1>

<%= render 'form', screenshot: @screenshot %>

<%= link_to 'Show', @screenshot %> |
<%= link_to 'Back', screenshots_path %>

web-screenshot-webapp/app/views/screenshots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Screenshots</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @screenshots.each do |screenshot| %>
      <tr>
        <td><%= screenshot.url %></td>
        <td><%= link_to 'Show', screenshot %></td>
        <td><%= link_to 'Edit', edit_screenshot_path(screenshot) %></td>
        <td><%= link_to 'Destroy', screenshot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Screenshot', new_screenshot_path %>

web-screenshot-webapp/app/views/screenshots/new.html.erb
<h1>New Screenshot</h1>

<%= render 'form', screenshot: @screenshot %>

<%= link_to 'Back', screenshots_path %>

web-screenshot-webapp/app/views/screenshots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @screenshot.url %>
</p>

<p>
  <strong>Screenshot:</strong>
  <% if @screenshot.image_exists? %>
    <%= link_to image_tag(@screenshot.screenshot_url, width: 300), @screenshot.screenshot_url %>
  <% else %>
    Now Processing...
  <% end %>
</p>

<%= link_to 'Edit', edit_screenshot_path(@screenshot) %> |
<%= link_to 'Back', screenshots_path %>